/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG_DASH_DASH = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_DASH_DASH_GT = 3,
  anon_sym_LT = 4,
  aux_sym_start_tag_token1 = 5,
  anon_sym_EQ = 6,
  anon_sym_GT = 7,
  anon_sym_LT_SLASH = 8,
  aux_sym_end_tag_token1 = 9,
  anon_sym_DQUOTE = 10,
  sym_text = 11,
  sym_source_file = 12,
  sym_comment = 13,
  sym_start_tag = 14,
  sym__full_tag = 15,
  sym_end_tag = 16,
  sym_attribute_name = 17,
  sym_attribute_value = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_start_tag_repeat1 = 20,
  aux_sym__full_tag_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_LT] = "<",
  [aux_sym_start_tag_token1] = "start_tag_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [aux_sym_end_tag_token1] = "end_tag_token1",
  [anon_sym_DQUOTE] = "\"",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_start_tag] = "start_tag",
  [sym__full_tag] = "_full_tag",
  [sym_end_tag] = "end_tag",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym__full_tag_repeat1] = "_full_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_start_tag_token1] = aux_sym_start_tag_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [aux_sym_end_tag_token1] = aux_sym_end_tag_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_start_tag] = sym_start_tag,
  [sym__full_tag] = sym__full_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym__full_tag_repeat1] = aux_sym__full_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_start_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_end_tag_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__full_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__full_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 14,
  [20] = 12,
  [21] = 15,
  [22] = 17,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 35,
  [37] = 27,
  [38] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(10);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(3);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_start_tag_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_end_tag_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [aux_sym_end_tag_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_comment] = STATE(7),
    [sym_start_tag] = STATE(3),
    [sym__full_tag] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(19), 1,
      sym_end_tag,
    STATE(6), 3,
      sym_comment,
      sym__full_tag,
      aux_sym__full_tag_repeat1,
  [24] = 7,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(20), 1,
      sym_end_tag,
    STATE(2), 3,
      sym_comment,
      sym__full_tag,
      aux_sym__full_tag_repeat1,
  [48] = 7,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    STATE(5), 1,
      sym_start_tag,
    STATE(14), 1,
      sym_end_tag,
    STATE(6), 3,
      sym_comment,
      sym__full_tag,
      aux_sym__full_tag_repeat1,
  [72] = 7,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    ACTIONS(19), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(12), 1,
      sym_end_tag,
    STATE(4), 3,
      sym_comment,
      sym__full_tag,
      aux_sym__full_tag_repeat1,
  [96] = 6,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(24), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(6), 3,
      sym_comment,
      sym__full_tag,
      aux_sym__full_tag_repeat1,
  [117] = 5,
    ACTIONS(5), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 3,
      sym_comment,
      sym__full_tag,
      aux_sym_source_file_repeat1,
  [135] = 5,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(39), 1,
      anon_sym_LT,
    STATE(3), 1,
      sym_start_tag,
    STATE(8), 3,
      sym_comment,
      sym__full_tag,
      aux_sym_source_file_repeat1,
  [153] = 4,
    ACTIONS(42), 1,
      anon_sym_GT,
    ACTIONS(44), 1,
      aux_sym_end_tag_token1,
    STATE(11), 1,
      aux_sym_start_tag_repeat1,
    STATE(18), 1,
      sym_attribute_name,
  [166] = 2,
    ACTIONS(48), 1,
      sym_text,
    ACTIONS(46), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [175] = 4,
    ACTIONS(44), 1,
      aux_sym_end_tag_token1,
    ACTIONS(50), 1,
      anon_sym_GT,
    STATE(13), 1,
      aux_sym_start_tag_repeat1,
    STATE(18), 1,
      sym_attribute_name,
  [188] = 2,
    ACTIONS(54), 1,
      sym_text,
    ACTIONS(52), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [197] = 4,
    ACTIONS(56), 1,
      anon_sym_GT,
    ACTIONS(58), 1,
      aux_sym_end_tag_token1,
    STATE(13), 1,
      aux_sym_start_tag_repeat1,
    STATE(18), 1,
      sym_attribute_name,
  [210] = 2,
    ACTIONS(63), 1,
      sym_text,
    ACTIONS(61), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [219] = 2,
    ACTIONS(67), 1,
      sym_text,
    ACTIONS(65), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [228] = 2,
    ACTIONS(71), 1,
      sym_text,
    ACTIONS(69), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [237] = 2,
    ACTIONS(75), 1,
      sym_text,
    ACTIONS(73), 3,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [246] = 2,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(79), 2,
      anon_sym_GT,
      aux_sym_end_tag_token1,
  [254] = 2,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
  [262] = 2,
    ACTIONS(52), 1,
      anon_sym_LT,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
  [270] = 2,
    ACTIONS(65), 1,
      anon_sym_LT,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
  [278] = 2,
    ACTIONS(73), 1,
      anon_sym_LT,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_LT_BANG_DASH_DASH,
  [286] = 1,
    ACTIONS(81), 3,
      anon_sym_EQ,
      anon_sym_GT,
      aux_sym_end_tag_token1,
  [292] = 1,
    ACTIONS(83), 2,
      anon_sym_GT,
      aux_sym_end_tag_token1,
  [297] = 2,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_attribute_value,
  [304] = 1,
    ACTIONS(87), 2,
      anon_sym_GT,
      aux_sym_end_tag_token1,
  [309] = 1,
    ACTIONS(89), 1,
      aux_sym_comment_token1,
  [313] = 1,
    ACTIONS(91), 1,
      aux_sym_end_tag_token1,
  [317] = 1,
    ACTIONS(93), 1,
      aux_sym_start_tag_token1,
  [321] = 1,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
  [325] = 1,
    ACTIONS(97), 1,
      anon_sym_DASH_DASH_GT,
  [329] = 1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [333] = 1,
    ACTIONS(101), 1,
      aux_sym_end_tag_token1,
  [337] = 1,
    ACTIONS(103), 1,
      anon_sym_DASH_DASH_GT,
  [341] = 1,
    ACTIONS(105), 1,
      anon_sym_GT,
  [345] = 1,
    ACTIONS(107), 1,
      anon_sym_GT,
  [349] = 1,
    ACTIONS(109), 1,
      aux_sym_comment_token1,
  [353] = 1,
    ACTIONS(111), 1,
      aux_sym_end_tag_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 135,
  [SMALL_STATE(9)] = 153,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 175,
  [SMALL_STATE(12)] = 188,
  [SMALL_STATE(13)] = 197,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 219,
  [SMALL_STATE(16)] = 228,
  [SMALL_STATE(17)] = 237,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 262,
  [SMALL_STATE(21)] = 270,
  [SMALL_STATE(22)] = 278,
  [SMALL_STATE(23)] = 286,
  [SMALL_STATE(24)] = 292,
  [SMALL_STATE(25)] = 297,
  [SMALL_STATE(26)] = 304,
  [SMALL_STATE(27)] = 309,
  [SMALL_STATE(28)] = 313,
  [SMALL_STATE(29)] = 317,
  [SMALL_STATE(30)] = 321,
  [SMALL_STATE(31)] = 325,
  [SMALL_STATE(32)] = 329,
  [SMALL_STATE(33)] = 333,
  [SMALL_STATE(34)] = 337,
  [SMALL_STATE(35)] = 341,
  [SMALL_STATE(36)] = 345,
  [SMALL_STATE(37)] = 349,
  [SMALL_STATE(38)] = 353,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__full_tag_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__full_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__full_tag, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__full_tag, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__full_tag, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__full_tag, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "html",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
